# Change these first
owner: theSoberSobber # Your GitHub organization or username, where this repository lives
repo: docker-manager-backend-healthcheck # The name of this repository

sites:
  - name: Docker Manager Backend
    url: https://dm-prod.1110777.xyz/health
  - name: Docker Manager Backend - Testing
    url: https://dm-testing.1110777.xyz/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: dm-status.1110777.xyz
  # baseUrl: /docker-manager-backend-healthcheck
  logoUrl: https://raw.githubusercontent.com/theSoberSobber/Docker-Manager/refs/heads/main/store_listing/docker-manager-logo.png
  name: Docker Manager
  introTitle: "**Docker Manager** is an Android App that allows you to manage your docker installation on remote from your mobile phone!"
  introMessage: This is a status page which monitoring prod and testing Docker Manager Backend deployments. Docker Manager backend is used to serve notifications of docker events on your server. Notifications are part of **Docker Manager Pro Plan**. Learn more [here](https://github.com/$OWNER/$REPO).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
